# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DSPDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dsp_Dialog(object):
    def setupUi(self, dsp_Dialog):
        dsp_Dialog.setObjectName("dsp_Dialog")
        dsp_Dialog.resize(329, 110)
        self.verticalLayout = QtWidgets.QVBoxLayout(dsp_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.former_button = QtWidgets.QPushButton(dsp_Dialog)
        self.former_button.setObjectName("former_button")
        self.horizontalLayout.addWidget(self.former_button)
        self.latter_button = QtWidgets.QPushButton(dsp_Dialog)
        self.latter_button.setObjectName("latter_button")
        self.horizontalLayout.addWidget(self.latter_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.hint_label = QtWidgets.QLabel(dsp_Dialog)
        self.hint_label.setObjectName("hint_label")
        self.verticalLayout.addWidget(self.hint_label)

        self.retranslateUi(dsp_Dialog)
        self.former_button.clicked.connect(self.former_button.hide)
        self.latter_button.clicked.connect(self.latter_button.hide)
        QtCore.QMetaObject.connectSlotsByName(dsp_Dialog)

    def retranslateUi(self, dsp_Dialog):
        _translate = QtCore.QCoreApplication.translate
        dsp_Dialog.setWindowTitle(_translate("dsp_Dialog", "手动双面打印"))
        self.former_button.setText(_translate("dsp_Dialog", "先"))
        self.latter_button.setText(_translate("dsp_Dialog", "后"))
        self.hint_label.setText(_translate("dsp_Dialog", "请按照先后顺序进行操作，正面打完后请将\n"
"出仓纸反着放回打印机入纸口进行反面打印"))
